
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\faqih\OneDrive\Dokumen\PlatformIO\Projects\Project Mikro\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("412x917")
window.configure(bg = "#EFD3CC")


canvas = Canvas(
    window,
    bg = "#EFD3CC",
    height = 917,
    width = 412,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    213.0,
    447.0,
    image=image_image_1
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    608.0,
    661.0,
    image=image_image_2
)

image_image_3 = PhotoImage(
    file=relative_to_assets("image_3.png"))
image_3 = canvas.create_image(
    284.0,
    955.0,
    image=image_image_3
)

canvas.create_text(
    33.0,
    352.0,
    anchor="nw",
    text="SMART TROLLEY",
    fill="#665353",
    font=("LondrinaSolid Regular", 40 * -1)
)

canvas.create_text(
    170.0,
    437.0,
    anchor="nw",
    text="LIST",
    fill="#000000",
    font=("Inter", 40 * -1)
)

canvas.create_rectangle(
    299.0,
    342.0,
    371.0,
    418.0,
    fill="#000000",
    outline="")

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=164.0,
    y=517.0,
    width=101.0,
    height=281.0
)

canvas.create_rectangle(
    126.0,
    636.0,
    309.0,
    798.0,
    fill="#000000",
    outline="")
window.resizable(False, False)
window.mainloop()
