
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage


OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\faqih\OneDrive\Dokumen\PlatformIO\Projects\Project Mikro\build\assets\frame2")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("412x917")
window.configure(bg = "#F1E4D9")


canvas = Canvas(
    window,
    bg = "#F1E4D9",
    height = 917,
    width = 412,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=31.0,
    y=47.0,
    width=53.0,
    height=37.0
)

canvas.create_text(
    84.0,
    42.0,
    anchor="nw",
    text="PRODUCT DETAIL",
    fill="#000000",
    font=("InriaSans Regular", 40 * -1)
)

image_image_1 = PhotoImage(
    file=relative_to_assets("image_1.png"))
image_1 = canvas.create_image(
    206.0,
    324.0,
    image=image_image_1
)

canvas.create_text(
    31.0,
    530.0,
    anchor="nw",
    text="MILK    750mL",
    fill="#151414",
    font=("LondrinaSolid Regular", 40 * -1)
)

canvas.create_text(
    31.0,
    591.0,
    anchor="nw",
    text="Rp. 18.500,00",
    fill="#000000",
    font=("LondrinaSolid Regular", 40 * -1)
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=23.0,
    y=663.0,
    width=366.0,
    height=89.0
)

image_image_2 = PhotoImage(
    file=relative_to_assets("image_2.png"))
image_2 = canvas.create_image(
    220.0,
    916.0,
    image=image_image_2
)
window.resizable(False, False)
window.mainloop()
